### ISSUE TITLE
Performance issue using 2 cameras

### ISSUE THREAD

**Issue by backinside** [inspirit/PS3EYEDriver#17]
It seems I'm experiencing performance degradation if I use 2 cameras
Running 2 separate processes does not seem to have this issue
Do you have any advice using multiple cameras?
At the moment I'm working on a single thread
Can I call ps3eye::PS3EYECam::updateDevices(); from multiple threads?

**Comment by backinside** [comment]
It seems the issue was with SDL
After removing the SDL code, calling the updateDevices once, I get a stable 60FPS from both cameras

**Comment by cboulay** [comment]
As you are another Windows user pushing the boundaries of what you can do with these devices, I just thought I'd warn you about something.

I have another (non camera) device that uses libusb's older non-context interface. I could not run that device and PS3EYEDriver at the same time when both devices were on the same USB host; the device halted all other libusb communication. I had to put this other device on my USB2-port and kept the PS3Eye on my USB3-port. I didn't have this problem in OSX even though both devices also use libusb in OSX.

I'm glad you posted this because it tells me it wouldn't be a huge waste of time to modify the device's program to use the new interface, as PS3EYEDriver does.

**Comment by backinside** [comment]
I've successfully grabbed the image of 2 cameras and read the values of the Move controller from a single thread
But I can only grab the move data after I read the images
If I poll the data from the Move or send data to the Move, I never get a new frame from any of the cameras
But If I send or receive data after a successful frame grab from both cameras, I can communicate with the Move, I can do that 60 times a second :)

**Comment by backinside** [comment]
Oh one more thing, I have to use a different USB port for the cameras, plugging them into an USB3 hub seems to kill the performance (~2FPS)

**Comment by cboulay** [comment]
@backinside , maybe conversations about the PSMove controller should move to the psmoveapi repository and/or the PSMove google group.

OK, so you do have similar issues with multiple cameras on the same host. Maybe the two USB ports you chose are on different hosts.

**Comment by inspirit** [comment]
updateDevices should be called only from one thread. at the moment there is single controller for all USB communication (read multiple cameras)
better way will be starting new thread with each new camera and update devices from it but this require a code rewrite and new USB manager implementation. 
In Linux they actually create new thread for each new driver instance.

**Comment by inspirit** [comment]
BTW: seems like this project gets more and more attention :) so i was wondering if people interested in rewriting it. Current implementation is more like a proof of concept. I was really planning to implement it in proper way with new threads for each new connected device etc. But that will require:
1. switch to c++11 to use std::thread. (i dont wan't to reimplement all this stuff for different platforms and i don't want to link with such monsters like Boost)
2. interface/API changes will most likely be global.
3. it will still need libusb. we can't get out of it unfortunately.

Let me know your thoughts.

**Comment by backinside** [comment]
Well I'm trying to put together a proof of concept, to see how we can optimize the setup
Currently my goal is to use 2 PSEye cameras to track a Move controller at 60FPS to accurately show it in a DK2 under tightly controlled conditions (like light, reflections, positions, etc)
If that works, than it might turn out, that we can use the PSEye for this purpose
If that's the case, I can invest more serious effort to stabilize the driver, even rewrite it
My fear is that the resolution of the camera might not be enough for us
But I'm more than happy to help any way I can
At the moment, the setup works, but I have some stability issues with the system
After a couple of seconds (~15) one of the cameras stops sending frames, and only responds after seconds
But I'll keep trying to improve the system, it might tour out to be an issue in my code :)
Even if I don't end up using this, I can help test it in various setups, so let me know if I can help :)
I would certainly not suggest to use boost, I would personally rather not even use std if possible
Maybe a super lightweight threading library, I don't think you need more than starting / stopping a thread and signalling the main thread, that should not be hard
Do you have some kind of description / documentation about the communication protocol?
Do you have an idea, what the new interface would look like?

**Comment by backinside** [comment]
I wonder, is the PlayStation Camera that Sony uses for VR is the same as the PS4 Camera?
Is that anything like the PSEye?

**Comment by cboulay** [comment]
@inspirit , I'm not sure if it's worth it to rewrite this library. I think a lot of the recent interest is for using the PSMove as a motion controller in virtual reality. As soon as the Vive is released in November, the Oculus Touch next ~June, and/or the PS4 camera hacks mature, there won't be much interest in the PSEye anymore. It's still super cheap for what it does so there might be some interest by people looking to build multi-cam computer vision setups, but I think that does not reflect the recent interest.

@backinside 

I don't think there are any super lightweight multi-platform threading libraries. Probably the simplest would be to use pthreads and win-pthreads on Windows.

The Morpheus uses the PS4 camera. The PS4 camera already has a small hacker community around it. See [here](https://github.com/bigboss-ps3dev/PS4EYECam) for example.

I have the PSMove working [coregistered](https://www.youtube.com/watch?v=AWoRb8UhSWU&feature=youtu.be) with the DK2 so I can view them both in the same space (using UE4, but the concept should be the same for Unity). I'm only using one camera though so accuracy does suffer a bit, especially in the PSEye-Z axis. It's OK for [my use](http://ottawa.ctvnews.ca/using-virtual-reality-to-relieve-parkinson-s-symptoms-1.2471025) but I plan to upgrade to a Vive as soon as possible, and we'll also be getting a $50k optical tracker sometime early next year, whenever the approved grant money makes it into our account. If you want any tips on coregistering then ping me offline.

**Comment by AGPX** [comment]
Same issue of backinside, with two cameras. I notice that the transfer slow down if they are connected to the same usb controller. And it not a multi-thread issue, because I have run two process: one read from cam 0 and the other from cam 1. Looks like that the asynchronous bulk transfer is slower. Probably an issue of the libusb library or the USB controller? It's very sad that a such nice (and the only one free!) library cannot handles more than one camera at time on the same controller (I have to handle 6 cameras!) :(

**Comment by inspirit** [comment]
well as u mentioned this is more like usblib/usb port issue, i cant see how the library rewrite may help with that. ps3eye support is native on linux platforms you can try to use some linux machine and connect several cameras to see if it will behave differently

**Comment by AGPX** [comment]
@inspirit I don't know about the native support of ps3eye on linux, I'll for sure give it a try. And if it works (excluding issues with my usb controller) I wish to rewrite the library using native Microsoft USB API in order to exclude libusb issues. Thank you.

**Comment by AGPX** [comment]
Ok, I have tried on linux, same behaviour. Now it's clear to me that is a limit of my dumb/slow/fake USB controller :((  (I definitely HATE notebooks!)

**Comment by inspirit** [comment]
thats what i was suspecting... 60fps really need nice through-output and i was experiencing broken buffers and slowdown myself even when i was testing with single camera on bad usb port/hub

**Comment by AGPX** [comment]
Ok, after further investigations I can conclude that it's not a problem of my USB controller. After I have read specification of my USB controller, it seem that it not so bad as I had thinked initially. So, (desperately) I bought the "CL Eye Platform SDK", but it had not worked. The SDK does not recognize the camera (not a single one). Looking at the forum, someone had solved through a system restore of a previous saved restore point. Since I installed several things (like the libusb-win32 driver, installed through the tool zadig), I decided to do the restore too. After this the device manager of the SDK has recognized the cameras! Then I tried to make a simple program that captures the frames of the two cameras at 640 x 480 60 FPS .... and it works like charm! I also tried to put the two cameras on the SAME USB 3.0 port (via the powered hub) .... and it still works like charm! Now, I don't really understand what this driver do to handle the PS3 cameras, but it works. So it's a software issue.

**Comment by cboulay** [comment]
In the future, when uninstall libusb for your cameras, all you have to do is go to device manager, right click on the camera and 'uninstall', but MAKE SURE to check the box to delete the driver file too.

Also, never install a new libusb driver for your camera OVER an old one (e.g., switching from WinUSB to libusbK). Always delete the old one first.
