### ISSUE TITLE
Openframeworks example fails

### ISSUE THREAD

**Issue by rootux** [inspirit/PS3EYEDriver#24]
Hey.
there is no eye->isNewFrame() in the driver.
am I missing anything?

**Comment by rovarma** [comment]
You're not missing anything; the OpenFrameworks and Cinder samples are broken since PR https://github.com/inspirit/PS3EYEDriver/pull/21.

It should be trivial to update the sample to work with the API changes as described in that PR (see https://github.com/inspirit/PS3EYEDriver/blob/master/sdl/main.cpp for a working example), but I'll see if I can update the OpenFrameworks & Cinder samples today.

**Comment by rootux** [comment]
Thanks. would love to see that happens :+1:

**Comment by rootux** [comment]
any news on this?

**Comment by rovarma** [comment]
Unfortunately I have been really busy with other matters and haven't gotten around to it yet. I'll try to get it done this week, but I can't guarantee that. In the meantime, you could consider making the change yourself; it should be pretty simple if you go off the SDL example.

**Comment by rovarma** [comment]
See https://github.com/inspirit/PS3EYEDriver/pull/25
